steps:
   - name: 'gcr.io/cloud-builders/docker'
     args: ['build', '-f' , 'trainer.dockerfile', '-t', 'gcr.io/positive-notch-374310/trainer-mnist', '.']
   - name: 'gcr.io/cloud-builders/docker'
     args: ['push', 'gcr.io/positive-notch-374310/testing']
