# # config_gpu.yaml
# workerPoolSpecs:
#    machineSpec:
#       machineType: n1-standard-8
#       acceleratorType: NVIDIA_TESLA_T4
#       acceleratorCount: 1
#    replicaCount: 1
#    containerSpec:
#       imageUri: gcr.io/positive-notch-374310/trainer


# config_cpu.yaml
workerPoolSpecs:
   machineSpec:
      machineType: n1-highmem-2
   replicaCount: 1
   containerSpec:
      imageUri: gcr.io/positive-notch-374310/trainer:3.1
      env:
         - name: WANDB_API_KEY
           value: 24e890c4ed63bff440bd2fc4ad73d1cb0ca74ab0
