wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.7
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    m:
    - 1: trainer/global_step
      6:
      - 3
    python_version: 3.10.6
    start_time: 1673258295.904194
    t:
      1:
      - 1
      - 9
      - 41
      - 50
      - 55
      2:
      - 1
      - 9
      - 41
      - 50
      - 55
      3:
      - 7
      - 23
      4: 3.10.6
      5: 0.13.7
      8:
      - 5
